# Generated by Django 6.0.6 on 2026-06-26 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('requirement', models.TextField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_opened', models.BooleanField(default=False)),
                ('email_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('link_clicked', models.BooleanField(default=False)),
                ('link_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('ai_category', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_priority', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
